name = "worker-stripe"
main = "./index.js"
compatibility_date = "2022-05-03"
kv_namespaces = [
  { binding = "PHOTOS", id = "7d6b49581ba9476d9adf950151ce096f" }
]
[vars]

# The necessary secrets are:
# - API_TOKEN
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these

